### ISSUE TITLE
no live tv in jellyfin

### ISSUE THREAD

**Issue by smoebody** [jellyfin/jellyfin-plugin-tvheadend#13]
after configuring the plugin i have new menu items of live-tv, tv-guide and tvheadend-recordings, but only the tvheadend-recordings show any content (the recordings of tv-headend). I can playback these recordings without problems.
However there are no channels, programms, guide, etc. all empty.

jellyfin-version: 10.4.1
tvheadend-version: 4.3-1804
tvheadend-plugin: 3.0.0.0

any idea?

**Comment by PythonSmith** [comment]
Same problem. I will try to dig into this problem
Using jellyfin-version 10.4.2
and Theadend 4.3-1804~gebb096804

**Comment by PythonSmith** [comment]
Found my problem: This logic says ignore channel with channel id <0
`                        if (message.containsField("channelNumber") && message.getInt("channelNumber") > 0) // use only channels with number > 0
                        {
                            _data.Add(channelID, message);
                        }`
For me the default channel id value is 0
So in a fresh setup we won't ever see channels
Solution:
1. Assign Channel ID for your channel in tvheadend and save
2. Refresh TV-Channel data in Jellyfin

**Comment by dkanada** [comment]
@smoebody were you still having issues?

**Comment by smoebody** [comment]
appearently #17 is preventing me from confirming the suggested workaround. I will report back, when i could take care of it.

**Comment by anthonylavado** [comment]
@smoebody It was fixed in #18 and merged?

**Comment by smoebody** [comment]
Live-TV now works for me.
