### ISSUE TITLE
Support 4K channels

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-plugin-tvheadend#6]
When configuring Tvheadend so that Jellyfin could collect the information of the channels, I observed a 4K channel does not appear in Jellyfin despite having been configured correctly, for example:

Tvheadend channel number:

37. HIT TV
38. EMISION 4K Pruebas
39. Boing

Jellyfin channel number:

37. HIT TV
39. Boing

**Comment by dkanada** [comment]
might be fixed with #18

**Comment by dkanada** [comment]
@97carmine can you check if version four is working for you?

**Comment by 97carmine** [comment]
Currently I can not prove it, the channel was broadcast temporarily.
