### ISSUE TITLE
unable to connect jellyfin to tvheadend

### ISSUE THREAD

**Issue by milouz1985** [jellyfin/jellyfin-plugin-tvheadend#70]
Hi,

I used the guide provided in jellyfin official documentation: https://jellyfin.org/docs/general/server/plugins/tvheadend/ but when I hit save, nothing happened. When I go back to plugin menu Tvheadend returns "Malfunctioned" without any clue on how to correct the error.
what can I do?

**Comment by crobibero** [comment]
Typically malfunctioned state happens when you attempt to install a plugin into a version of the server that it doesn't support.

**Comment by languagemaniac** [comment]
Hi, I'm having the same issue. Just installed tvheadend, loaded the plugin, followed the instructions [here](https://jellyfin.org/docs/general/server/plugins/tvheadend/).

I set the allowed range for jellyfin user to 0.0.0.0/0, the plugin state is "malfunction". I think I need some help

**Comment by milouz1985** [comment]
i do not understand, but it begun to function correctly without any modification.
