### ISSUE TITLE
NotSupported on Jellyfin 10.9.0

### ISSUE THREAD

**Issue by Azelphur** [jellyfin/jellyfin-plugin-tvheadend#79]
I imagine work needs to be done to get this working with 10.9.0, but of course now that it is released/stable, this plugin no longer works. :(

**Comment by crobibero** [comment]
Unfortunately I have no way of testing this plugin so I was unable to update it.

Someone did start the upgrade process however: https://github.com/jellyfin/jellyfin-plugin-tvheadend/pull/78

**Comment by emveepee** [comment]
@crobibero I went to update the nextvpvr addon and  was wondering what happened to LiveTvTunerInfo and LiveTvTunerStatus Trying to compile tvheadend I see the same problem.  What are there replacements

**Comment by crobibero** [comment]
I have no way of testing either NextPVR or TvHeadEnd, but does `ITunerHostManager` provide what is needed?

**Comment by emveepee** [comment]
> I have no way of testing either NextPVR or TvHeadEnd, but does `ITunerHostManager` provide what is needed?

They were being used by MP/Jellyfin in the past not the plugin, maybe the callbacks can just be removed.

**Comment by SlowmoDK** [comment]
> Unfortunately I have no way of testing this plugin so I was unable to update it.
> 
> Someone did start the upgrade process however: #78

Can we get someone in here who can ? nothing seems to be happening at #78  
@joshuaboniface

**Comment by lomion0815** [comment]
I finalized the changes to support 10.9 with PR https://github.com/jellyfin/jellyfin-plugin-tvheadend/pull/81.
It was tested with branch unstable.

**Comment by crobibero** [comment]
plugin v12 is now available.

**Comment by tristan-k** [comment]
Can anybod confirm the new version is working fine with Jellyfin `10.9.6`. I just tried to connect to my TVHeadend installation but there are no channels in the corresponding Live TV section. I followed the [guide](https://jellyfin.org/docs/general/server/plugins/tvheadend/) and my channels are numbered.

My jellyfin log says

```
Jun 28 16:55:30 jellyfin jellyfin[113]: [16:55:30] [ERR] [TVHclient] HTSConnectionAsync.open: exception caught
Jun 28 16:55:30 jellyfin jellyfin[113]: System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known
Jun 28 16:55:30 jellyfin jellyfin[113]:    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Null>
Jun 28 16:55:30 jellyfin jellyfin[113]:    at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
Jun 28 16:55:30 jellyfin jellyfin[113]:    at TVHeadEnd.HTSP.HTSConnectionAsync.open(String hostname, Int32 port)
Jun 28 16:55:32 jellyfin jellyfin[113]: [16:55:32] [ERR] [TVHclient] HTSConnectionAsync.open: exception caught
Jun 28 16:55:32 jellyfin jellyfin[113]: System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known
Jun 28 16:55:32 jellyfin jellyfin[113]:    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Null>
Jun 28 16:55:32 jellyfin jellyfin[113]:    at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
Jun 28 16:55:32 jellyfin jellyfin[113]:    at TVHeadEnd.HTSP.HTSConnectionAsync.open(String hostname, Int32 port)
```

**Comment by seiichiro0185** [comment]
I'm on Jellyfin 10.9.7 and TVH plugin version 12 works just fine (also worked on 10.9.6).
Your log messages sound like a DNS-problem. Maybe try setting the IP-address for your TVH server in the plugin settings (from the messages I assume you put the hostname there)?

**Comment by tristan-k** [comment]
The error messages reads like a network problem but I'm pretty sure that it is not the issue. The Jellyfin instance is running inside a proxmox lxc  and the the tvheadend server `192.168.178.81` is runnging inside another lxc with docker. I can ping the tvheadend server from inside the jellyfin lxc and connect to the ports. 

```
root@jellyfin:~# ping 192.168.178.81
PING 192.168.178.81 (192.168.178.81) 56(84) bytes of data.
64 bytes from 192.168.178.81: icmp_seq=1 ttl=64 time=0.134 ms
64 bytes from 192.168.178.81: icmp_seq=2 ttl=64 time=0.062 ms
64 bytes from 192.168.178.81: icmp_seq=3 ttl=64 time=0.039 ms

root@jellyfin:~# nc -zv 192.168.178.81 9982
Connection to 192.168.178.81 9982 port [tcp/*] succeeded!
root@jellyfin:~# nc -zv 192.168.178.81 9981
Connection to 192.168.178.81 9981 port [tcp/*] succeeded!
```

**Comment by Mdullaway** [comment]
I'm getting the same error as above with Jellyfin 10.9.11:

[2024-09-22 09:22:25.784 +00:00] [ERR] [26] TVHeadEnd.HTSP.HTSConnectionAsync: [TVHclient] HTSConnectionAsync.open: exception caught
System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Nullable`1 startingTimestamp)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
   at TVHeadEnd.HTSP.HTSConnectionAsync.open(String hostname, Int32 port)

I have verified that access to TVHeadEnd is possible from other clients (such as Kodi) using the same credentials, ports, ip address, etc. Again this flags as a network issue, but not one that seems to actually be present!

Any and all advice to resolve would be appreciated.

Thank you

**Comment by arcangelnew** [comment]
Im experiencing the same issue, and I doubt it's a network porblem because NextPVR plugin running in same host with same ip has no porblem to connect.
